### ISSUE TITLE
It's not working in swift 3 

### ISSUE THREAD

**Issue by MusabBasheer** [zsybupt/SwiftSignalR#1]

**Comment by 8ggmaker** [comment]
@MusabBasheer I will add Swift3 support recently

**Comment by MusabBasheer** [comment]
I appreciate your efforts but I need it as soon as possible :) Any advice

**Comment by MusabBasheer** [comment]
I work on chat application and i use ObjSignalR  library but it have a delay in send and receive  👍

**Comment by 8ggmaker** [comment]
I don't know why there is a  delay in send and receive using ObjSignalR, do you use WebSocket for transport? Maybe you can open an issue in its repository, and I will add swift3.0 branch this week.

**Comment by MusabBasheer** [comment]
Thanks 👍

**Comment by MusabBasheer** [comment]
Can you create pod for your project so i can use it 👍 Thanks

**Comment by MusabBasheer** [comment]
@zsybupt  can you help in this because i have release after two days , thanks

**Comment by 8ggmaker** [comment]
@MusabBasheer I don't know, maybe I can add Swift3.0 tonight if everything goes well, but I have no plan to create pod now, because the longpolling transport is not ready yet, you can clone or download it, and build it to use in your project.

**Comment by MusabBasheer** [comment]
@zsybupt Thanks 👍

**Comment by 8ggmaker** [comment]
@MusabBasheer add dev-swift3 branch, some codes are transformed automatically by XCode8, maybe I will do some changes later, but it can be used now, I have tested the sample app in SwiftSignalRTest target. If there is a bug, let me know, thanks

**Comment by MusabBasheer** [comment]
@zsybupt  Thanks a lot 👍
